@startuml

!$client = "客户端(Client)"
!$authServer = "授权服务器(Authorization Server)"
!$consent = "授权同意页(Consent screen)"
!$resServer = "资源服务器(Resource Server)"

"$client" -> "$authServer": 跳转
note left
client_id
redirect_uri: abc.com/callback
response_type: code
scope:Profile,contact
state
end note

"$authServer"-> "$authServer": 没有登录情况下，需要账号密码登录

"$authServer" -> "$consent": 重定向
"$consent" -> "$consent": 点击确认授权按钮
"$consent" -> "$client":重定向到 abc.com/callback(code=<Authorization Code>)
note right
Authorization Code
end note

"$client" -> "$authServer": 请求获取访问令牌(access token)
note left
code
client_id
client_secret
redirect_uri
grant_type: authorization code
end note

"$client" <- "$authServer": 返回访问令牌(access token)
"$client" -> "$resServer" : 请求获取资源(携带 access token)
"$client" <- "$resServer" : 返回资源


@enduml