@startuml

!$client = "客户端(Client)"
!$resServer = "资源服务器(Resource Server)"

"$client" -> "$resServer": 请求资源
note left
client_id
client_secret
scope
user
password
grant_type: Encrypted value
end note

"$client" <- "$resServer" : 返回资源


@enduml